// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A translation AI agent triggered by a hotkey.
 *
 * - translateText - A function that handles the translation process.
 * - TranslateTextInput - The input type for the translateText function.
 * - TranslateTextOutput - The return type for the translateText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TranslateTextInputSchema = z.object({
  text: z.string().describe('The text to translate.'),
  targetLanguage: z.string().describe('The target language for translation.'),
  promptOverride: z.string().optional().describe('Optional override for the translation prompt.'),
});
export type TranslateTextInput = z.infer<typeof TranslateTextInputSchema>;

const TranslateTextOutputSchema = z.object({
  translation: z.string().describe('The translated text.'),
});
export type TranslateTextOutput = z.infer<typeof TranslateTextOutputSchema>;

export async function translateText(input: TranslateTextInput): Promise<TranslateTextOutput> {
  return translateTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'translateTextPrompt',
  input: {schema: TranslateTextInputSchema},
  output: {schema: TranslateTextOutputSchema},
  prompt: `Translate the following text into {{targetLanguage}}.\n\nText: {{{text}}}`,
  system: `You are a translation expert. Your goal is to translate text accurately and fluently. Consider the context and intent of the text when translating.`,
});

const translateTextFlow = ai.defineFlow(
  {
    name: 'translateTextFlow',
    inputSchema: TranslateTextInputSchema,
    outputSchema: TranslateTextOutputSchema,
  },
  async input => {
    // If a prompt override is provided, use it instead of the default prompt.
    const finalPrompt = input.promptOverride ?
      ai.definePrompt({
        name: 'translateTextPromptOverride',
        input: {schema: TranslateTextInputSchema},
        output: {schema: TranslateTextOutputSchema},
        prompt: input.promptOverride,
      }) :
      prompt;

    const {output} = await finalPrompt(input);
    return output!;
  }
);
